name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew check --info

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/src/main/java
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations:
            ${{github.workspace}}/src/app/build/reports/coverage/staging/debug/report.xml::jacoco
